#!/bin/bash

# Update package sources
apt-get update

# Install Nginx
apt-get install nginx -y

# Configure Nginx to listen on port 80
sed -i 's/listen 80 default_server/listen 80/' /etc/nginx/sites-available/default

# Set Nginx root page content
echo 'Hello World!' > /var/www/html/index.html

# Restart Nginx
service nginx restart
