#!/usr/bin/env bash
# gives you information about the Bestschool file using the if/else statement

file="Bestschool"
if [ -e "$file" ]
then
    echo "$file file exists"
    if [ -s "$file" ]
	then
		echo "Bestschool file is not empty"
    else
		echo "Bestschool file is empty"
    fi
    if [ -f "$file" ]
	then
		echo "Bestschool is a regular file"
    fi
else
    echo "Bestschool file does not exist"
fi
